name: Playwright DemoQA CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x 

      - name: Install dependencies
        run: dotnet restore PlaywrightDemoQA.csproj

      - name: Build project
        run: dotnet build PlaywrightDemoQA.csproj --configuration Release --no-restore

      - name: Install Playwright Browsers

        run: pwsh bin/Release/net10.0/playwright.ps1 install --with-deps

      - name: Run Tests

        run: dotnet test PlaywrightDemoQA.csproj --configuration Release --no-build --logger:"trx;LogFileName=results.trx"

      - name: Upload Playwright Traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces

          path: bin/Release/net10.0/playwright-traces/

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: bin/Release/net10.0/screenshots/

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: bin/Release/net10.0/allure-results/
