name: Playwright DemoQA CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x 

      - name: Install dependencies
        # Указываем путь к проекту: Папка/Файл
        run: dotnet restore PlaywrightDemoQA/PlaywrightDemoQA.csproj

      - name: Build project
        run: dotnet build PlaywrightDemoQA/PlaywrightDemoQA.csproj --configuration Release --no-restore

      - name: Install Playwright Browsers
        # Скрипт установки лежит в выходной папке проекта
        run: pwsh PlaywrightDemoQA/bin/Release/net10.0/playwright.ps1 install --with-deps

      - name: Run Tests
        run: dotnet test PlaywrightDemoQA/PlaywrightDemoQA.csproj --configuration Release --no-build --logger:"trx;LogFileName=results.trx"

      - name: Upload Playwright Traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: PlaywrightDemoQA/bin/Release/net10.0/playwright-traces/

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: PlaywrightDemoQA/bin/Release/net10.0/screenshots/

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: PlaywrightDemoQA/bin/Release/net10.0/allure-results/
